# Generated by Django 4.2 on 2023-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='palettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(max_length=50)),
                ('color_2', models.CharField(max_length=50)),
                ('color_3', models.CharField(max_length=50)),
                ('color_4', models.CharField(max_length=50)),
                ('color_5', models.CharField(max_length=50)),
            ],
        ),
    ]
