# Generated by Django 4.2 on 2023-06-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palette_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='palettes',
            new_name='Palette',
        ),
    ]
